function [] = tutorial(ModoJogo,fig) 
clf;%limpa ecrã
% reset da tecla inicial
set(fig, 'UserData', 'nada');
axis off; %retira grafico

% apresentação tutorial dependendo do jogo
switch ModoJogo
    case 1 % modo facil
        %titulo
            txt = text(0.5, 1,' ', 'FontSize', 30, 'HorizontalAlignment', 'center','FontWeight','bold','Color','b');%posição de escrita
            set(txt, 'String', 'TUTORIAL: Modo Fácil');
            %tutorial (selecionada opçao 1)
            txt = text(0.5, 0.5, '', 'FontSize', 25, 'HorizontalAlignment', 'center','Color','y');%posição de escrita
            %texto principal
            set(txt, 'String', sprintf(['     ' ... 
                                        '\n Encaixa blocos 3D para preencher fatias do tabuleiro.\n ' ...
                                        'Fatias cheias dão pontos! Se a torre bater no teto, é GAME OVER!S' ...
                                        '\n\n               ' ...
                                        '\nNão há gravidade neste modo. Pensa com calma!' ...
                                        '\nA peça flutua no topo à espera da tua jogada.' ...
                                        '\n\n            ' ...
                                        '\nSetas: Movem a peça no ar (eixos X e Y).' ...
                                        '\nEspaço: Confirma a jogada e atira a peça para o fundo.' ...
                                        '\nESC: Abre o menu de Pausa.']));
            %titulos topicos
            txt = text(0.5, 0.43, '', 'FontSize', 25, 'HorizontalAlignment', 'center','Color','r');%posição de escrita
            set(txt, 'String', sprintf(['OBJETIVO:' ...
                                        '\n \n ' ...
                                        '                     ' ...
                                        '\n\nComo Jogar:' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n\nControlos:' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n\n\nPressione qualquer tecla para continuar...']));
            waitforbuttonpress;
    case 2 % modo medio
        %titulo
            txt = text(0.5, 1,' ', 'FontSize', 30, 'HorizontalAlignment', 'center','FontWeight','bold','Color','b');%posição de escrita
            set(txt, 'String', 'TUTORIAL: Modo Médio');
            %tutorial (selecionada opçao 1)
            txt = text(0.5, 0.5, '', 'FontSize', 25, 'HorizontalAlignment', 'center','Color','y');%posição de escrita
            %texto principal
            set(txt, 'String', sprintf(['     ' ... 
                                        '\n Encaixa blocos 3D para preencher fatias do tabuleiro.\n ' ...
                                        'Fatias cheias dão pontos a DOBRAR! Se a torre bater no teto, é GAME OVER!' ...
                                        '\n\n               ' ...
                                        '\nNeste modo, as peças caem sozinhas ao longo do tempo!' ...
                                        '\nQuantas mais fatias eliminares, mais RÁPIDO o jogo fica.' ...
                                        '\nEntre cada peça, o jogo pausa para respirares.' ...
                                        '\n\n            ' ...
                                        '\nSetas: Movem a peça no ar (eixos X e Y).' ...
                                        '\nEspaço: Inicia a próxima peça OU atira a peça atual para o fundo.' ...
                                        '\nESC: Abre o menu de Pausa.']));
            %titulos topicos
            txt = text(0.5, 0.43, '', 'FontSize', 25, 'HorizontalAlignment', 'center','Color','r');%posição de escrita
            set(txt, 'String', sprintf(['OBJETIVO:' ...
                                        '\n \n ' ...
                                        '                     ' ...
                                        '\n\nComo Jogar:' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n\nControlos:' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n\n\nPressione qualquer tecla para continuar...']));
            waitforbuttonpress;
    case 3 % modo dificil
        %titulo
            txt = text(0.5, 1,' ', 'FontSize', 30, 'HorizontalAlignment', 'center','FontWeight','bold','Color','b');%posição de escrita
            set(txt, 'String', 'TUTORIAL: Modo Difícil');
            %tutorial (selecionada opçao 1)
            txt = text(0.5, 0.5, '', 'FontSize', 25, 'HorizontalAlignment', 'center','Color','y');%posição de escrita
            %texto principal
            set(txt, 'String', sprintf(['     ' ... 
                                        '\n Encaixa blocos 3D para preencher fatias do tabuleiro.\n ' ...
                                        'Neste nível ganhas o TRIPLO dos pontos! Bater no teto é GAME OVER!' ...
                                        '\n\n               ' ...
                                        '\nA gravidade não perdoa e o jogo NÃO ESPERA por ti!' ...
                                        '\nAMal uma peça toca no fundo, a próxima começa a cair imediatamente.' ...
                                        '\nAtenção: Destruir fatias faz o jogo ficar cada vez mais RÁPIDO.' ...
                                        '\n\n            ' ...
                                        '\nSetas: Movem a peça no ar (eixos X e Y).' ...
                                        '\nEspaço: Atira a peça para o fundo instantaneamente.' ...
                                        '\nESC: Abre o menu de Pausa.']));
            %titulos topicos
            txt = text(0.5, 0.43, '', 'FontSize', 25, 'HorizontalAlignment', 'center','Color','r');%posição de escrita
            set(txt, 'String', sprintf(['OBJETIVO:' ...
                                        '\n \n ' ...
                                        '                     ' ...
                                        '\n\nComo Jogar:' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n\nControlos:' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n ' ...
                                        '\n\n\nPressione qualquer tecla para continuar...']));
            waitforbuttonpress;
    otherwise
        return;
end

end